# Generated by Django 5.2.7 on 2025-10-19 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0003_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Relay Control', max_length=100)),
                ('relay1_status', models.BooleanField(default=False, verbose_name='RELAY 1')),
                ('relay2_status', models.BooleanField(default=False, verbose_name='RELAY 2')),
                ('relay3_status', models.BooleanField(default=False, verbose_name='RELAY 3')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Relay Controller',
                'verbose_name_plural': 'Relay Controllers',
            },
        ),
    ]
