# Generated by Django 5.2.7 on 2025-10-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0004_relay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_high', models.FloatField(default=35.0, help_text='เมื่ออุณหภูมิเกินค่านี้จะเปิด Relay 1', verbose_name='อุณหภูมิสูงสุด (°C)')),
                ('temperature_low', models.FloatField(default=20.0, help_text='เมื่ออุณหภูมิต่ำกว่าค่านี้จะเปิด Relay 1', verbose_name='อุณหภูมิต่ำสุด (°C)')),
                ('humidity_high', models.FloatField(default=80.0, help_text='เมื่อความชื้นเกินค่านี้จะเปิด Relay 1', verbose_name='ความชื้นสูงสุด (%)')),
                ('humidity_low', models.FloatField(default=30.0, help_text='เมื่อความชื้นต่ำกว่าค่านี้จะเปิด Relay 1', verbose_name='ความชื้นต่ำสุด (%)')),
                ('mode', models.CharField(choices=[('AUTO', 'Auto - ควบคุมอัตโนมัติ'), ('MANUAL', 'Manual - ควบคุมด้วยมือ')], default='MANUAL', max_length=10, verbose_name='โหมดควบคุม')),
                ('relay1_auto_enabled', models.BooleanField(default=True, verbose_name='เปิดใช้งาน Relay 1 อัตโนมัติ')),
                ('alarm_active', models.BooleanField(default=False, help_text='True = กำลังแจ้งเตือน (Relay 1 เปิด), False = ปกติ', verbose_name='สถานะ Alarm')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='เวลาแจ้งเตือนล่าสุด')),
                ('alarm_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='สาเหตุการแจ้งเตือน')),
                ('hysteresis_percentage', models.FloatField(default=2.0, help_text='ช่วงความแตกต่างกลับคืนสู่สถานะปกติ (ป้องกันการสั่นของ Relay)', verbose_name='Hysteresis (%)')),
                ('average_window', models.IntegerField(default=10, help_text='จำนวนข้อมูลล่าสุดที่ใช้คำนวณค่าเฉลี่ย', verbose_name='จำนวน Readings สำหรับค่าเฉลี่ย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Threshold Setting',
                'verbose_name_plural': 'Threshold Settings',
            },
        ),
    ]
