# Generated by Django 5.2.7 on 2025-10-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0004_relay'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='board_id',
            field=models.CharField(default='v2_board', help_text='Unique identifier for the ESP32 board', max_length=50),
        ),
        migrations.AddField(
            model_name='relay',
            name='board_id',
            field=models.CharField(default='v2_board', help_text='Unique identifier for the ESP32 board', max_length=50),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='board_id',
            field=models.CharField(default='v2_board', help_text='Unique identifier for the ESP32 board', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('board_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='relay',
            unique_together={('board_id', 'name')},
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['board_id', '-timestamp'], name='iot_dashboa_board_i_6ede4d_idx'),
        ),
    ]
