# Generated by Django 5.2.7 on 2025-10-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0005_thresholdsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_temperature', models.FloatField(verbose_name='อุณหภูมิปัจจุบัน (°C)')),
                ('current_humidity', models.FloatField(verbose_name='ความชื้นปัจจุบัน (%)')),
                ('weather_forecast', models.JSONField(blank=True, default=dict, verbose_name='ข้อมูลพยากรณ์อากาศ')),
                ('decision', models.CharField(choices=[('ON', 'เปิด Relay 2'), ('OFF', 'ปิด Relay 2')], max_length=3, verbose_name='การตัดสินใจ')),
                ('confidence', models.FloatField(default=0.0, verbose_name='ความมั่นใจ')),
                ('reasoning', models.TextField(help_text='คำอธิบายการตัดสินใจจาก AI', verbose_name='เหตุผล')),
                ('relay2_previous_status', models.BooleanField(default=False, verbose_name='สถานะ Relay 2 ก่อนหน้า')),
                ('relay2_new_status', models.BooleanField(default=False, verbose_name='สถานะ Relay 2 ใหม่')),
                ('action_taken', models.BooleanField(default=False, help_text='True = มีการเปลี่ยนสถานะ Relay 2', verbose_name='มีการเปลี่ยนแปลง')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่บันทึก')),
            ],
            options={
                'verbose_name': 'AI Decision Log',
                'verbose_name_plural': 'AI Decision Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
