# Generated by Django 5.2.7 on 2025-10-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0006_aidecisionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidecisionlog',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='aidecisionlog',
            name='current_humidity',
        ),
        migrations.RemoveField(
            model_name='aidecisionlog',
            name='current_temperature',
        ),
        migrations.RemoveField(
            model_name='aidecisionlog',
            name='relay2_new_status',
        ),
        migrations.RemoveField(
            model_name='aidecisionlog',
            name='relay2_previous_status',
        ),
        migrations.RemoveField(
            model_name='aidecisionlog',
            name='weather_forecast',
        ),
        migrations.AddField(
            model_name='aidecisionlog',
            name='command_sent',
            field=models.BooleanField(default=False, verbose_name='ส่งคำสั่งสำเร็จ'),
        ),
        migrations.AddField(
            model_name='aidecisionlog',
            name='relay_status',
            field=models.BooleanField(default=False, verbose_name='สถานะ Relay 2'),
        ),
        migrations.AddField(
            model_name='aidecisionlog',
            name='weather_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='ข้อมูลสภาพอากาศ'),
        ),
        migrations.AlterField(
            model_name='aidecisionlog',
            name='decision',
            field=models.CharField(help_text='on = เปิด, off = ปิด', max_length=10, verbose_name='การตัดสินใจ'),
        ),
    ]
