# Generated by Django 6.0.3 on 2026-03-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0009_deviceconfig_ds18b20'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='ds18b20_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='DS18B20 (°C)'),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
