# Generated by Django 6.0.3 on 2026-03-06 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0010_add_ds18b20_to_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_number', models.IntegerField(choices=[(1, 'RELAY 1'), (2, 'RELAY 2'), (3, 'RELAY 3')], verbose_name='Relay')),
                ('new_state', models.BooleanField(verbose_name='สถานะใหม่')),
                ('previous_state', models.BooleanField(blank=True, null=True, verbose_name='สถานะเดิม')),
                ('source', models.CharField(choices=[('mqtt', 'ESP32 (MQTT feedback)'), ('ai_agent', 'AI Agent'), ('threshold', 'Threshold Auto-control'), ('manual', 'Manual (Admin)')], default='mqtt', max_length=20, verbose_name='แหล่งที่สั่ง')),
                ('reason', models.TextField(blank=True, verbose_name='เหตุผล')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='เวลา')),
            ],
            options={
                'verbose_name': 'Relay Log',
                'verbose_name_plural': 'Relay Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
