# Generated by Django 6.0.3 on 2026-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0011_add_relaylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay1_name', models.CharField(default='RELAY 1', max_length=50, verbose_name='ชื่อ RELAY 1')),
                ('relay2_name', models.CharField(default='RELAY 2', max_length=50, verbose_name='ชื่อ RELAY 2')),
                ('relay3_name', models.CharField(default='RELAY 3', max_length=50, verbose_name='ชื่อ RELAY 3')),
                ('led_name', models.CharField(default='Onboard LED', max_length=50, verbose_name='ชื่อ LED')),
            ],
            options={
                'verbose_name': 'Output Settings',
                'verbose_name_plural': 'Output Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='relay',
            options={'verbose_name': 'Output Monitor', 'verbose_name_plural': 'Output Monitoring'},
        ),
    ]
