# Generated by Django 6.0.3 on 2026-03-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0012_add_relaysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', help_text='OpenWeatherMap API Key — ดูได้จาก https://openweathermap.org/api', max_length=100, verbose_name='API Key')),
                ('location', models.CharField(default='Nakhon Si Thammarat,TH', help_text='รูปแบบ: "ชื่อเมือง,รหัสประเทศ" เช่น Bangkok,TH หรือ London,GB', max_length=100, verbose_name='Location')),
                ('units', models.CharField(choices=[('metric', 'Metric (°C, m/s)'), ('imperial', 'Imperial (°F, mph)')], default='metric', max_length=10, verbose_name='หน่วย')),
                ('is_enabled', models.BooleanField(default=True, help_text='ปิดเพื่อหยุดดึงข้อมูลอากาศ (AI Agent จะทำงานโดยไม่ใช้ข้อมูลอากาศ)', verbose_name='เปิดใช้งาน Weather API')),
                ('last_tested', models.DateTimeField(blank=True, null=True, verbose_name='ทดสอบล่าสุด')),
                ('last_test_ok', models.BooleanField(blank=True, null=True, verbose_name='ผลทดสอบล่าสุด')),
                ('last_test_msg', models.CharField(blank=True, max_length=200, verbose_name='ข้อความผลทดสอบ')),
            ],
            options={
                'verbose_name': 'Weather API Settings',
                'verbose_name_plural': 'Weather API Settings',
            },
        ),
    ]
