# Generated by Django 6.0.3 on 2026-03-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0013_add_weatherapisettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', help_text='Google Gemini API Key — ดูได้จาก https://makersuite.google.com/app/apikey', max_length=200, verbose_name='Gemini API Key')),
                ('model_name', models.CharField(default='gemini-2.0-flash', help_text='ชื่อ model เช่น gemini-2.0-flash, gemini-1.5-pro', max_length=100, verbose_name='Model Name')),
                ('interval_minutes', models.PositiveIntegerField(default=60, help_text='AI Agent จะวิเคราะห์และตัดสินใจทุกกี่นาที (ค่าน้อย = บ่อยขึ้น = ใช้ quota เร็วขึ้น)', verbose_name='รอบการวิเคราะห์ (นาที)')),
                ('is_enabled', models.BooleanField(default=True, help_text='ปิดเพื่อหยุด AI Agent ไม่ให้ส่งคำสั่งควบคุม Relay', verbose_name='เปิดใช้งาน AI Agent')),
                ('last_tested', models.DateTimeField(blank=True, null=True, verbose_name='ทดสอบล่าสุด')),
                ('last_test_ok', models.BooleanField(blank=True, null=True, verbose_name='ผลทดสอบล่าสุด')),
                ('last_test_msg', models.CharField(blank=True, max_length=500, verbose_name='ข้อความผลทดสอบ')),
            ],
            options={
                'verbose_name': 'Gemini AI Settings',
                'verbose_name_plural': 'Gemini AI Settings',
            },
        ),
    ]
