# Generated by Django 6.0.3 on 2026-03-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0014_add_geminiaisettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geminiaisettings',
            options={'verbose_name': 'AI Agent Settings', 'verbose_name_plural': 'AI Agent Settings'},
        ),
        migrations.AddField(
            model_name='geminiaisettings',
            name='provider',
            field=models.CharField(choices=[('gemini', '🔵 Google Gemini (Direct)'), ('openrouter', '🟢 OpenRouter (Multi-model)')], default='openrouter', help_text='Gemini Direct = ใช้ Google SDK โดยตรง | OpenRouter = OpenAI-compatible เลือก model ได้เยอะมาก', max_length=20, verbose_name='AI Provider'),
        ),
        migrations.AlterField(
            model_name='geminiaisettings',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='• Gemini: ดูได้จาก https://makersuite.google.com/app/apikey | • OpenRouter: ดูได้จาก https://openrouter.ai/keys', max_length=200, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='geminiaisettings',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='AI Agent จะวิเคราะห์และตัดสินใจทุกกี่นาที (ค่าน้อย = บ่อยขึ้น = ใช้ token เร็วขึ้น)', verbose_name='รอบการวิเคราะห์ (นาที)'),
        ),
        migrations.AlterField(
            model_name='geminiaisettings',
            name='last_test_msg',
            field=models.CharField(blank=True, max_length=1000, verbose_name='ข้อความผลทดสอบ'),
        ),
        migrations.AlterField(
            model_name='geminiaisettings',
            name='model_name',
            field=models.CharField(default='google/gemini-2.0-flash', help_text='ตัวอย่าง OpenRouter: google/gemini-2.0-flash, anthropic/claude-3.5-sonnet, meta-llama/llama-3.3-70b-instruct, openai/gpt-4o-mini | ดูทั้งหมดได้ที่ https://openrouter.ai/models', max_length=150, verbose_name='Model Name'),
        ),
    ]
