# Generated by Django 5.2.11 on 2026-03-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0024_remove_push_all_from_n8npushsettings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='weatherlog',
            new_name='iot_dashboa_timesta_0c1fb5_idx',
            old_name='weatherlog_ts_idx',
        ),
        migrations.AlterField(
            model_name='geminiaisettings',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='OpenRouter API Key — ดูได้จาก https://openrouter.ai/keys', max_length=200, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='geminiaisettings',
            name='model_name',
            field=models.CharField(default='google/gemini-2.0-flash-001', help_text='ตัวอย่าง OpenRouter: google/gemini-2.0-flash-001, anthropic/claude-3.5-sonnet, meta-llama/llama-3.3-70b-instruct, openai/gpt-4o-mini | ดูทั้งหมดได้ที่ https://openrouter.ai/models', max_length=150, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='n8npushsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='n8npushsettings',
            name='webhook_snapshot',
            field=models.URLField(blank=True, default='', help_text='ตัวอย่าง: http://192.168.1.100:5678/webhook/iot-snapshot — URL นี้เป็น endpoint เดียวที่ใช้ (ส่งทุก event รวมกัน)', max_length=500, verbose_name='Snapshot Webhook URL'),
        ),
        migrations.AlterField(
            model_name='weatherapisettings',
            name='last_test_msg',
            field=models.TextField(blank=True, verbose_name='ข้อความผลทดสอบ'),
        ),
    ]
