# Generated by Django 5.2.11 on 2026-03-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_dashboard', '0025_fix_last_test_msg_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminiaisettings',
            name='last_test_msg',
            field=models.TextField(blank=True, verbose_name='ข้อความผลทดสอบ'),
        ),
    ]
